name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'appflow-ai' }}

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com
      - name: Setup and publish nightly
        run: |
          node build/nightly/prepare.js
          npm i zrender@npm:zrender-nightly
          npm ci
          npm ls zrender
          node build/nightly/post.js
          npm run release
          npm run test
          npm run test:dts
          npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
